language: python
python:
  - "3.4"
  - "3.5"
before_install:  
  - pip install --upgrade pip
matrix:
        include:
                - python: '3.6' # Black requires Python 3.6+
                  install:
                          - pip install -r requirements.txt
                          - pip install black
                  script:
                          - black --check readit setup.py
                          - python setup.py install
                          - python setup.py check -r -s
                          - pytest
install:
  - pip install -r requirements.txt
script:
  - python setup.py install
  - python setup.py check -r -s
  - pytest
